#!/usr/bin/env zsh
POKERUSERNAME=Steven

if [ "$#" -ne 2 ]; then
  echo "Usage: poker <API URL> <GAME_ID>"
  exit
fi

export POKER_API_URL=$1
export GAME_ID=$2
join_poker_response=$(curl -d '{"name": "'$POKERUSERNAME'"}' -H "Content-Type: application/json" -X POST "$POKER_API_URL"/join/"$GAME_ID")
PLAYER_ID=$(echo "$join_poker_response" | jq -r .playerId)
export PLAYER_ID
zsh
