#!/usr/bin/env zsh

if [ "$#" -ne 1 ]; then
  echo "Usage: vote <point value>"
  exit
fi

curl -d '{"playerId": "'"$PLAYER_ID"'", "pointValue": "'"$1"'"}' -H "Content-Type: application/json" \
-X POST "$POKER_API_URL"/"$GAME_ID"
